# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:11
      # See https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:10.16.0
        environment:
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - /root/.cache/Cypress

      # run tests!
      - run:
          name: Test Code Style
          command: yarn eslint src

      - run:
          name: Run unit tests
          command: yarn test

      - run:
          name: Run e2e tests
          command: yarn feature-test

      - store_artifacts:
          path: cypress/videos

      - store_artifacts:
          path: cypress/screenshots

      - run:
          name: Release to npm
          command: yarn semantic-release
