const FIELDS = {
  FIRST_NAME: 'first_name',
  LAST_NAME: 'last_name',
  EMAIL: 'email',
  GROUP: 'fundraising_group',
  SEGMENT: 'fundraising_segment',
  ORG_NAME: 'org_name',
  INDUSTRY_TYPE: 'industry_type',
  ORG_SIZE: 'org_size',
  JOB: 'job_title',
  LINE1: 'address_line_1',
  LINE2: 'address_line_2',
  LINE3: 'address_line_3',
  TOWN: 'town',
  POSTCODE: 'postcode',
  FUNDRAISING_PACK: 'fundraising_pack',
  TARGET_TEXT: 'fundraising_target_text',
  TARGET_POUNDS: 'fundraising_target_pounds',
  OVER_EIGHTEEN: 'over_eighteen',
  CONFIRM_EMAIL: 'confirm_email',
  PHONE: 'phone',
  TSHIRT_SIZE: 'tshirt_size',
  PAGE_TITLE: 'jg_page_title',
  PAGE_STORY: 'jg_page_story',
  // MP fields; matching the names supplied by the MP component itself
  MP_EMAIL: 'mp_email',
  MP_LINE1: 'mp_address1',
  MP_LINE2: 'mp_address2',
  MP_LINE3: 'mp_address3',
  MP_TOWN: 'mp_town',
  MP_POSTCODE: 'mp_postcode',
  MP_COUNTRY: 'mp_country',
  MP_MOBILE: 'mp_mobile',
  MP_PHONE: 'mp_phone',
  MP_PERM_EMAIL: 'mp_permissionEmail',
  MP_PERM_PHONE: 'mp_permissionPhone',
  MP_PERM_POST: 'mp_permissionPost',
  MP_PERM_SMS: 'mp_permissionSMS'
};

export default FIELDS;
